### DISCUSSION TITLE
About making formatting changes to the code directly

### DISCUSSION THREAD

**Discussion by DecimalTurn** [Beakerboy/VBA-Linter#95] [General]
In its current state, the linter produces an error message for each instance where code isn't formatted properly, however it doesn't fix the formatting issue.

The problem with this is that adding the linter as an Action to a GitHub project means that you could end up with a lot of manual formatting to do in order to make the linter return ✅. For example, there is currently 3000+ errors detected for https://github.com/sancarn/stdVBA ([latest job](https://github.com/sancarn/stdVBA/actions/runs/8593444670/job/23544955663) - [commit](https://github.com/sancarn/stdVBA/commit/3a80c2c107795d75b5ff45487564c4241da56371)). 

@Beakerboy, would you consider that making those changes directly with the linter and pushing those to a new branch a desirable feature?

**Comment by Beakerboy** [comment]
There are two separate parts to this. The linter can create new files with the errors fixed, but you would have to use git to push the changes. There are separate GitHub actions that can do this, such as:

```yml
    - name: Commit files
       run: |
        git config --local user.email "me@me.com"
        git config --local user.name "Me"
        mv fixed/* src
        git add src/*
        git commit -m "Add linted files"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
```

Fixing files is in the plan, but my free time is limited.
